services:
  # ----------Microservices----------
  gateway:
    restart: always
    build:
      context: ./src/gateway
    entrypoint: ["dotnet", "gateway.dll"]
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=compose
    depends_on:
      - repository
      - identity
      - syncing
      - issue

  repository:
    restart: always
    build:
      context: .
      dockerfile: src/services/repository/Dockerfile
    entrypoint: ["dotnet", "repository.dll"]
    ports:
      - "5247:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=compose
      - MassTransit__Host=rabbitmq://rabbitmq:5672
    depends_on:
      repo-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  identity:
    restart: always
    build:
      context: ./src/services/identity
    entrypoint: ["dotnet", "identity.dll"]
    ports:
      - "5246:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=compose
    depends_on:
      - identity-db

  syncing:
    restart: always
    build:
      context: ./src/services/syncing
    entrypoint: ["dotnet", "syncing.dll"]
    ports:
      - "5248:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=compose
      - GitHub__ClientId=${GitHub__ClientId}
      - GitHub__ClientSecret=${GitHub__ClientSecret}
    depends_on:
      - identity

  issue:
    restart: always
    build:
      context: .
      dockerfile: src/services/repository/Dockerfile
    entrypoint: ["dotnet", "issue.dll"]
    ports:
      - "5249:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=compose
      - MassTransit__Host=rabbitmq://rabbitmq:5672
    depends_on:
      - issue-db

  # frontend:
  #   restart: always
  #   build:
  #     context: ./src/frontend
  #   ports:
  #     - "3000:80"

  # ----------Database----------
  identity-db:
    restart: always
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_db
    ports:
      - "5433:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data

  repo-db:
    restart: always
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repo_db
    ports:
      - "5432:5432"
    volumes:
      - repo_data:/var/lib/postgresql/data

  issue-db:
    restart: always
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue_db
    ports:
      - "5434:5432"
    volumes:
      - issue_data:/var/lib/postgresql/data

  # ----------MessageQueue----------
  rabbitmq:
    restart: always
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_ERLANG_COOKIE=MYSECRETCOOKIE
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672" #AMQP
      - "15672:15672" #Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  repo_data:
  identity_data:
  issue_data:
  rabbitmq_data:
